#app:
#    resource: "@AppBundle/Controller/"
#    type:     annotation
#


#request_querystring:
#  path: /querystring/
#  defaults: { _controller: AppBundle:Default:requestQuerystring }

#request_post:
#  path: /post/
#  defaults: { _controller: AppBundle:Default:requestPost }
#  methods: [POST]

calc_add:
    path: /add/
    defaults: {_controller:AppBundle:Calculator:add}
    methods: [POST]
    requirements:
         param1: '\d+'
         param2: '\d+'
calc_substract:
    path: /substract/{param1}/
    defaults: {_controller:AppBundle:Calculator:substract}
    
calc_multiply:
    path: /multiply/
    defaults: {_controller:AppBundle:Calculator:multiply}

